#!/bin/sh

for dir in . sudokuRapidConsole ; do
    echo Doing all in ${dir} ...
    (cd $dir
    echo '  'Creating files needed by automake ...
    touch NEWS README AUTHORS ChangeLog
    echo '  'Running aclocal ...
    aclocal
    echo '  'Generating configure ...
    autoconf
    echo '  'Generating config.h.in ...
    autoheader
    echo '  'Generating Makefile.in ...
    automake -a)
done

